//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule_Creator_V2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schedule_Creator_V2.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT 
        ///	INTO 
        ///		[UWGB].[Availability] 
        ///	(id, dayOfTheWeek, startTime, endTime) 
        ///VALUES 
        ///		(@id, @dayOfTheWeek, @startTime, @endTime).
        /// </summary>
        internal static string CreateAvailability {
            get {
                return ResourceManager.GetString("CreateAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE 
        ///	Schedule_Creator_V2
        ///ON 
        ///	(
        ///		NAME = Schedule_Creator_V2, 
        ///		FILENAME = &apos;{databaseFileName}&apos;
        ///	) 
        ///LOG ON 
        ///	(
        ///		NAME = Schedule_Creator_V2_Log, 
        ///		FILENAME = &apos;{logFileName}&apos;).
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///    [UWGB].[DaysOff] 
        ///    (id, Date, reason) 
        ///VALUES 
        ///    (@id, @date, @reason).
        /// </summary>
        internal static string CreateDaysOff {
            get {
                return ResourceManager.GetString("CreateDaysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///    [UWGB].[JobSettings]
        ///    (DayOfWeek, OpeningTime, ClosingTime)
        ///VALUES
        ///    (@day, @openingTime, @closingTime).
        /// </summary>
        internal static string CreateJobSettings {
            get {
                return ResourceManager.GetString("CreateJobSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM
        ///    [UWGB].[Schedule]
        ///WHERE
        ///    scheduleName = @scheduleName
        ///INSERT INTO
        ///    [UWGB].[Schedule]
        ///    ([dayOfWeek], staffID, scheduleName)
        ///VALUES
        ///    (@dayOfWeek, @staffID, @scheduleName).
        /// </summary>
        internal static string CreateSchedule {
            get {
                return ResourceManager.GetString("CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SCHEMA [UWGB] AUTHORIZATION dbo.
        /// </summary>
        internal static string CreateSchemas {
            get {
                return ResourceManager.GetString("CreateSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///    [UWGB].[Staff] 
        ///    (fName, mName, lName, position, email, belayCert) 
        ///VALUES 
        ///    (@fName, @mName, @lName, @position, @email, @belayCert).
        /// </summary>
        internal static string CreateStaff {
            get {
                return ResourceManager.GetString("CreateStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [UWGB].[Availability] (
        ///    [id]           INT      NOT NULL,
        ///    [dayOfTheWeek] INT      NOT NULL,
        ///    [startTime]    TIME (2) NOT NULL,
        ///    [endTime]      TIME (2) NOT NULL
        ///);
        ///
        ///CREATE TABLE [UWGB].[DaysOff] (
        ///    [id]     INT           NOT NULL,
        ///    [Date]   DATE          NOT NULL,
        ///    [reason] NVARCHAR (50) NOT NULL
        ///);
        ///
        ///CREATE TABLE [UWGB].[JobSettings] (
        ///    [DayOfWeek]   NVARCHAR (50) NOT NULL,
        ///    [OpeningTime] TIME (2)      NOT NULL,
        ///    [ClosingTime] TIME (2)      NOT NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE 
        ///	FROM 
        ///		[UWGB].[Availability] 
        ///WHERE 
        ///	id = @id.
        /// </summary>
        internal static string DeleteAllAvailability {
            get {
                return ResourceManager.GetString("DeleteAllAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [UWGB].[JobSettings].
        /// </summary>
        internal static string DeleteAllJobSettings {
            get {
                return ResourceManager.GetString("DeleteAllJobSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///    [UWGB].[DaysOff] 
        ///WHERE 
        ///    id = @id AND Date = @date.
        /// </summary>
        internal static string DeleteDaysOff {
            get {
                return ResourceManager.GetString("DeleteDaysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///	FROM
        ///		[UWGB].[JobSettings]
        ///WHERE
        ///		DayOfWeek = @DayOfWeek.
        /// </summary>
        internal static string DeleteJobSettingsOnDay {
            get {
                return ResourceManager.GetString("DeleteJobSettingsOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT 
        ///    scheduleName
        ///FROM
        ///    [UWGB].[Schedule].
        /// </summary>
        internal static string ReadAllScheduleNames {
            get {
                return ResourceManager.GetString("ReadAllScheduleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	* 
        ///FROM 
        ///	[UWGB].[Availability] 
        ///WHERE 
        ///	id = @id.
        /// </summary>
        internal static string ReadAvailByID {
            get {
                return ResourceManager.GetString("ReadAvailByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	* 
        ///FROM 
        ///	[UWGB].[Availability] 
        ///WHERE 
        ///	@id = id.
        /// </summary>
        internal static string ReadAvailForStaffByID {
            get {
                return ResourceManager.GetString("ReadAvailForStaffByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	* 
        ///FROM 
        ///	[UWGB].[DaysOff].
        /// </summary>
        internal static string ReadDaysOff {
            get {
                return ResourceManager.GetString("ReadDaysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    *
        ///FROM
        ///    [UWGB].[JobSettings].
        /// </summary>
        internal static string ReadJobSettings {
            get {
                return ResourceManager.GetString("ReadJobSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Distinct
        ///    DayOfWeek
        ///FROM
        ///    [UWGB].[JobSettings].
        /// </summary>
        internal static string ReadJobSettingsDays {
            get {
                return ResourceManager.GetString("ReadJobSettingsDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM
        ///	[UWGB].[Schedule].
        /// </summary>
        internal static string ReadSchedule {
            get {
                return ResourceManager.GetString("ReadSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM
        ///	[UWGB].[Schedule]
        ///WHERE
        ///	scheduleName = @scheduleName.
        /// </summary>
        internal static string ReadScheduleByScheduleName {
            get {
                return ResourceManager.GetString("ReadScheduleByScheduleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM
        ///	[UWGB].[Schedule]
        ///WHERE
        ///	dayOfWeek = @dayOfWeek.
        /// </summary>
        internal static string ReadScheduleOnDay {
            get {
                return ResourceManager.GetString("ReadScheduleOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM
        ///	[UWGB].[Staff];.
        /// </summary>
        internal static string ReadStaff {
            get {
                return ResourceManager.GetString("ReadStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    *
        ///FROM 
        ///    [UWGB].[Staff]
        ///WHERE 
        ///    id IN (
        ///        SELECT 
        ///            id
        ///        FROM 
        ///            [UWGB].[Availability]
        ///        WHERE 
        ///            dayOfTheWeek = @dayOfTheWeek
        ///);.
        /// </summary>
        internal static string ReadStaffAvailOnDay {
            get {
                return ResourceManager.GetString("ReadStaffAvailOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	* 
        ///FROM 
        ///	[UWGB].[Staff] 
        ///WHERE 
        ///	id = @id.
        /// </summary>
        internal static string ReadStaffByID {
            get {
                return ResourceManager.GetString("ReadStaffByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    s.id, s.fName, s.lName, a.dayOfTheWeek, a.startTime, a.endTime
        ///FROM
        ///    [UWGB].[Staff] s
        ///RIGHT JOIN
        ///    [UWGB].[Availability] a
        ///ON
        ///
        ///    s.id = a.id
        ///WHERE
        ///    a.dayOfTheWeek = @day.
        /// </summary>
        internal static string ReadStaffNamesAndAvailOnDay {
            get {
                return ResourceManager.GetString("ReadStaffNamesAndAvailOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///    a.id,
        ///    a.dayOfTheWeek,
        ///    a.startTime,
        ///    a.endTime,
        ///    s.fName,
        ///    s.mName,
        ///    s.lName,
        ///    s.position,
        ///    s.email,
        ///    s.belayCert,
        ///    s.certifiedOn,
        ///    s.expiresOn
        ///FROM UWGB.Availability AS a
        ///INNER JOIN UWGB.Staff AS s
        ///    ON a.id = s.id;.
        /// </summary>
        internal static string ReadStaffWithNoAvail {
            get {
                return ResourceManager.GetString("ReadStaffWithNoAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 
        ///    [UWGB].[Staff]
        ///SET 
        ///    belayCert = @belayCert,
        ///    certifiedOn = @certifiedOn,
        ///    expiresOn = @expiresOn
        ///WHERE 
        ///    id = @id.
        /// </summary>
        internal static string UpdateBelayCert {
            get {
                return ResourceManager.GetString("UpdateBelayCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 
        ///	[UWGB].[Staff] 
        ///SET 
        ///	fName = @fName, 
        ///	mName = @mName, 
        ///	lName = @lName, 
        ///	position = @position, 
        ///	email = @email 
        ///WHERE 
        ///	id = @id.
        /// </summary>
        internal static string UpdateStaff {
            get {
                return ResourceManager.GetString("UpdateStaff", resourceCulture);
            }
        }
    }
}
