namespace Schedule_Creator_V2.Models.Records
{
    public record AutoGeneratedScheduleRow(
        int? mondayStaffId,
        int? tuesdayStaffId,
        int? wednesdayStaffId,
        int? thursdayStaffId,
        int? fridayStaffId,
        int? saturdayStaffId,
        int? sundayStaffId
        );
}
