using Schedule_Creator_V2.Models.Records;
using System.Text.RegularExpressions;

namespace Schedule_Creator_V2.Services
{
    internal static class AutoBuildScheduleService
    {
        private const string AutoGeneratedSchedulePrefix = "Auto Generated Schedule";

        public static List<AutoGeneratedScheduleRow> BuildAutoScheduleRows(int staffPerDay, IEnumerable<int>? excludedStaffIds = null, int maxRows = 10)
        {
            if (staffPerDay < 1)
            {
                return new List<AutoGeneratedScheduleRow>();
            }

            HashSet<int> excludedStaffSet = excludedStaffIds == null
                ? new HashSet<int>()
                : excludedStaffIds.ToHashSet();

            Dictionary<DayOfWeek, List<int>> staffByDay = GetStaffAvailabilityByDay(excludedStaffSet);

            int maxAvailableStaffForAnyDay = staffByDay.Values
                .Where(staffIds => staffIds.Count > 0)
                .Select(staffIds => staffIds.Count)
                .DefaultIfEmpty(0)
                .Max();

            if (maxAvailableStaffForAnyDay == 0)
            {
                return new List<AutoGeneratedScheduleRow>();
            }

            int rowCount = Math.Min(staffPerDay, maxRows);

            List<AutoGeneratedScheduleRow> rows = new List<AutoGeneratedScheduleRow>();

            for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
            {
                rows.Add(new AutoGeneratedScheduleRow(
                    TryGetStaffId(staffByDay, DayOfWeek.Monday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Tuesday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Wednesday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Thursday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Friday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Saturday, rowIndex),
                    TryGetStaffId(staffByDay, DayOfWeek.Sunday, rowIndex)
                    ));
            }

            return rows;
        }

        public static string BuildNextAutoGeneratedScheduleName()
        {
            List<string> scheduleNames = DatabaseRead.ReadAllScheduleNames();

            Regex autoScheduleRegex = new Regex($"^{Regex.Escape(AutoGeneratedSchedulePrefix)}\\s+(\\d+)$");

            int maxScheduleNumber = 0;

            foreach (string scheduleName in scheduleNames)
            {
                Match match = autoScheduleRegex.Match(scheduleName);

                if (!match.Success)
                {
                    continue;
                }

                if (!int.TryParse(match.Groups[1].Value, out int scheduleNumber))
                {
                    continue;
                }

                if (scheduleNumber > maxScheduleNumber)
                {
                    maxScheduleNumber = scheduleNumber;
                }
            }

            return $"{AutoGeneratedSchedulePrefix} {maxScheduleNumber + 1}";
        }

        private static Dictionary<DayOfWeek, List<int>> GetStaffAvailabilityByDay(HashSet<int> excludedStaffIds)
        {
            DayOfWeek[] allDays =
            {
                DayOfWeek.Monday,
                DayOfWeek.Tuesday,
                DayOfWeek.Wednesday,
                DayOfWeek.Thursday,
                DayOfWeek.Friday,
                DayOfWeek.Saturday,
                DayOfWeek.Sunday
            };

            Dictionary<DayOfWeek, List<int>> returnDict = new Dictionary<DayOfWeek, List<int>>();

            foreach (DayOfWeek day in allDays)
            {
                returnDict.Add(
                    day,
                    DatabaseRead.ReadStaffNamesAndAvailOnDay(day)
                        .Select(staff => staff.id)
                        .Where(staffId => !excludedStaffIds.Contains(staffId))
                        .ToList());
            }

            return returnDict;
        }

        private static int? TryGetStaffId(Dictionary<DayOfWeek, List<int>> staffByDay, DayOfWeek day, int rowIndex)
        {
            if (!staffByDay.TryGetValue(day, out List<int>? staffIds))
            {
                return null;
            }

            if (staffIds.Count <= rowIndex)
            {
                return null;
            }

            return staffIds[rowIndex];
        }
    }
}
