using Schedule_Creator_V2.Models;
using Schedule_Creator_V2.Models.Enums;
using Schedule_Creator_V2.Models.Records;
using System.Text.RegularExpressions;

namespace Schedule_Creator_V2.Services
{
    internal static class AutoBuildScheduleService
    {
        private const string AutoGeneratedSchedulePrefix = "Auto Generated Schedule";

        private static readonly HashSet<Positions> LeadershipPositions = new HashSet<Positions>
        {
            Positions.Shift_Lead,
            Positions.Lead_Supervisor,
            Positions.Lead_Route_Setter,
            Positions.Graduate_Assistant
        };

        public static List<AutoGeneratedScheduleRow> BuildAutoScheduleRows(int staffPerDay, IEnumerable<int>? excludedStaffIds = null, int maxRows = 10)
        {
            if (staffPerDay < 1)
            {
                return new List<AutoGeneratedScheduleRow>();
            }

            HashSet<int> excludedStaffSet = excludedStaffIds == null
                ? new HashSet<int>()
                : excludedStaffIds.ToHashSet();

            Dictionary<int, Staff> staffById = DatabaseRead.ReadStaff()
                .Where(staff => !excludedStaffSet.Contains(staff.id))
                .ToDictionary(staff => staff.id, staff => staff);

            if (staffById.Count == 0)
            {
                return new List<AutoGeneratedScheduleRow>();
            }

            Dictionary<DayOfWeek, JobSettings> jobSettingsByDay = DatabaseRead.ReadJobSettings()
                .GroupBy(settings => settings.dayOfWeek)
                .ToDictionary(group => group.Key, group => group.First());

            Dictionary<DayOfWeek, List<int>> eligibleStaffByDay = GetEligibleStaffByDay(staffById, jobSettingsByDay);

            int maxAvailableStaffForAnyDay = eligibleStaffByDay.Values
                .Where(staffIds => staffIds.Count > 0)
                .Select(staffIds => staffIds.Count)
                .DefaultIfEmpty(0)
                .Max();

            if (maxAvailableStaffForAnyDay == 0)
            {
                return new List<AutoGeneratedScheduleRow>();
            }

            int rowCount = Math.Min(staffPerDay, maxRows);
            Dictionary<DayOfWeek, List<int?>> assignedIdsByDay = BuildAssignments(eligibleStaffByDay, staffById, rowCount);

            List<AutoGeneratedScheduleRow> rows = new List<AutoGeneratedScheduleRow>();

            for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
            {
                rows.Add(new AutoGeneratedScheduleRow(
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Monday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Tuesday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Wednesday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Thursday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Friday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Saturday, rowIndex),
                    TryGetStaffId(assignedIdsByDay, DayOfWeek.Sunday, rowIndex)
                    ));
            }

            return rows;
        }

        public static string BuildNextAutoGeneratedScheduleName()
        {
            List<string> scheduleNames = DatabaseRead.ReadAllScheduleNames();

            Regex autoScheduleRegex = new Regex($"^{Regex.Escape(AutoGeneratedSchedulePrefix)}\\s+(\\d+)$");

            int maxScheduleNumber = 0;

            foreach (string scheduleName in scheduleNames)
            {
                Match match = autoScheduleRegex.Match(scheduleName);

                if (!match.Success)
                {
                    continue;
                }

                if (!int.TryParse(match.Groups[1].Value, out int scheduleNumber))
                {
                    continue;
                }

                if (scheduleNumber > maxScheduleNumber)
                {
                    maxScheduleNumber = scheduleNumber;
                }
            }

            return $"{AutoGeneratedSchedulePrefix} {maxScheduleNumber + 1}";
        }

        private static Dictionary<DayOfWeek, List<int>> GetEligibleStaffByDay(
            Dictionary<int, Staff> staffById,
            Dictionary<DayOfWeek, JobSettings> jobSettingsByDay)
        {
            DayOfWeek[] allDays =
            {
                DayOfWeek.Monday,
                DayOfWeek.Tuesday,
                DayOfWeek.Wednesday,
                DayOfWeek.Thursday,
                DayOfWeek.Friday,
                DayOfWeek.Saturday,
                DayOfWeek.Sunday
            };

            Dictionary<DayOfWeek, List<int>> returnDict = new Dictionary<DayOfWeek, List<int>>();

            foreach (DayOfWeek day in allDays)
            {
                if (!jobSettingsByDay.TryGetValue(day, out JobSettings? settings))
                {
                    returnDict.Add(day, new List<int>());
                    continue;
                }

                List<int> eligibleIds = DatabaseRead.ReadStaffNamesAndAvailOnDay(day)
                    .Where(avail => staffById.ContainsKey(avail.id))
                    .Where(avail => OverlapsOpenHours(avail, settings))
                    .Select(avail => avail.id)
                    .Distinct()
                    .ToList();

                returnDict.Add(day, eligibleIds);
            }

            return returnDict;
        }

        private static Dictionary<DayOfWeek, List<int?>> BuildAssignments(
            Dictionary<DayOfWeek, List<int>> eligibleStaffByDay,
            Dictionary<int, Staff> staffById,
            int rowCount)
        {
            Dictionary<int, int> assignmentCounts = staffById.Keys.ToDictionary(staffId => staffId, _ => 0);

            DayOfWeek[] allDays =
            {
                DayOfWeek.Monday,
                DayOfWeek.Tuesday,
                DayOfWeek.Wednesday,
                DayOfWeek.Thursday,
                DayOfWeek.Friday,
                DayOfWeek.Saturday,
                DayOfWeek.Sunday
            };

            Dictionary<DayOfWeek, List<int?>> assignedIdsByDay = new Dictionary<DayOfWeek, List<int?>>();

            foreach (DayOfWeek day in allDays)
            {
                if (!eligibleStaffByDay.TryGetValue(day, out List<int>? eligibleIds) || eligibleIds.Count == 0)
                {
                    assignedIdsByDay[day] = Enumerable.Repeat<int?>(null, rowCount).ToList();
                    continue;
                }

                HashSet<int> usedOnDay = new HashSet<int>();
                List<int?> assignedForDay = new List<int?>();

                List<int> leaderCandidates = eligibleIds
                    .Where(staffId => LeadershipPositions.Contains(staffById[staffId].position))
                    .ToList();

                List<int> attendantCandidates = eligibleIds
                    .Where(staffId => staffById[staffId].position == Positions.Attendant)
                    .ToList();

                int? requiredLeaderId = PickBestCandidate(leaderCandidates, assignmentCounts, usedOnDay);
                bool leaderWasAssigned = false;

                if (requiredLeaderId != null)
                {
                    assignedForDay.Add(requiredLeaderId);
                    usedOnDay.Add(requiredLeaderId.Value);
                    assignmentCounts[requiredLeaderId.Value]++;
                    leaderWasAssigned = true;
                }

                while (assignedForDay.Count < rowCount)
                {
                    int? nextStaffId = PickBestCandidate(attendantCandidates, assignmentCounts, usedOnDay);

                    if (nextStaffId == null)
                    {
                        List<int> fallbackCandidates = eligibleIds
                            .Where(staffId => !usedOnDay.Contains(staffId))
                            .Where(staffId => !leaderWasAssigned || !LeadershipPositions.Contains(staffById[staffId].position))
                            .ToList();

                        nextStaffId = PickBestCandidate(fallbackCandidates, assignmentCounts, usedOnDay);
                    }

                    if (nextStaffId == null)
                    {
                        nextStaffId = PickBestCandidate(eligibleIds, assignmentCounts, usedOnDay);
                    }

                    if (nextStaffId == null)
                    {
                        assignedForDay.Add(null);
                        continue;
                    }

                    assignedForDay.Add(nextStaffId);
                    usedOnDay.Add(nextStaffId.Value);
                    assignmentCounts[nextStaffId.Value]++;
                }

                assignedIdsByDay[day] = assignedForDay;
            }

            return assignedIdsByDay;
        }

        private static int? PickBestCandidate(List<int> candidateIds, Dictionary<int, int> assignmentCounts, HashSet<int> usedOnDay)
        {
            return candidateIds
                .Where(staffId => !usedOnDay.Contains(staffId))
                .OrderBy(staffId => assignmentCounts[staffId])
                .ThenBy(staffId => staffId)
                .Cast<int?>()
                .FirstOrDefault();
        }

        private static bool OverlapsOpenHours(StaffNameAndAvail avail, JobSettings settings)
        {
            return avail.startTime < settings.closingTime && avail.endTime > settings.openingTime;
        }

        private static int? TryGetStaffId(Dictionary<DayOfWeek, List<int?>> assignedIdsByDay, DayOfWeek day, int rowIndex)
        {
            if (!assignedIdsByDay.TryGetValue(day, out List<int?>? staffIds))
            {
                return null;
            }

            if (staffIds.Count <= rowIndex)
            {
                return null;
            }

            return staffIds[rowIndex];
        }
    }
}
